nelmio_api_doc:
    documentation:
        info:
            title: Product Service
            description: Most powerfull service
            version: RELEASE
    areas: # to filter documented areas
        path_patterns:
            - ^/api/product(?!/doc$) # Accepts routes under /api except /api/doc